### Description of Notebook

This notebook reads the entire 5GB news data set and the price dataset from huggingface, and filters out tech stocks that our project focuses on. It then saves these filtered datasets as "tech_news.csv" and "tech_prices.csv" in the Data folder

In [1]:
import pandas as pd
import numpy as np

In [2]:
all_news = pd.read_csv("Data/News.csv")

C:\Users\Jerry\AppData\Local\Temp\ipykernel_26108\1780632359.py:1: DtypeWarning: Columns (2,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  all_news = pd.read_csv("Data/News.csv")

In [12]:
all_news['Date'] = pd.to_datetime(all_news['Date'], format='%Y-%m-%d %H:%M:%S %Z', utc=True)

In [14]:
all_news["Date"][0]

Timestamp('2020-06-05 06:30:54+0000', tz='UTC')

In [63]:
all_news.head()

,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
0,2020-06-05 06:30:54+00:00,Stocks That Hit 52-Week Highs On Friday,A,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-06-03 06:45:20+00:00,Stocks That Hit 52-Week Highs On Wednesday,A,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-05-26 00:30:07+00:00,71 Biggest Movers From Friday,A,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-05-22 08:45:06+00:00,46 Stocks Moving In Friday's Mid-Day Session,A,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-05-22 07:38:59+00:00,B of A Securities Maintains Neutral on Agilent...,A,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
# List of tech stocks competing with Apple
tech_rivals = ['AAPL', 'ADBE', 'AMD', 'AMZN', 'BBK', 'GOOGL', 'GRMN', 'HPQ', 'IBM', 'INTC', 'NFLX', 'NVDA', 'ORCL', 'TSLA']

# Filter the DataFrame
tech_news = all_news[all_news["Stock_symbol"].isin(tech_rivals)]

tech_news.head()

,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
6680,2020-06-10 07:33:26+00:00,Tech Stocks And FAANGS Strong Again To Start D...,AAPL,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,NaN,NaN,NaN,NaN,NaN,NaN
6681,2020-06-10 04:14:08+00:00,10 Biggest Price Target Changes For Wednesday,AAPL,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
6682,2020-06-10 03:53:47+00:00,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",AAPL,https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
6683,2020-06-10 03:19:25+00:00,"Deutsche Bank Maintains Buy on Apple, Raises P...",AAPL,https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
6684,2020-06-10 02:27:11+00:00,Apple To Let Users Trade In Their Mac Computer...,AAPL,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
tech_news["Date"].min()

Timestamp('2009-08-16 00:00:00+0000', tz='UTC')

In [29]:
tech_news.to_csv("Data/tech_news.csv")

In [59]:
all_prices_df = pd.concat(
    [
        pd.read_csv(f"Data/Prices/{ticker}.csv").assign(
            Stock_symbol=ticker,
            Date=lambda df: pd.to_datetime(df["date"], errors="coerce")  # Auto-detect format
        )
        for ticker in tech_rivals
    ],
    ignore_index=True
)

filtered_prices_df = all_prices_df[all_prices_df["Date"] >= '08/15/2009']

filtered_prices_df

,date,open,high,low,close,adj close,volume,Stock_symbol,Date
0,2023-12-28,194.139999,194.660004,193.169998,193.580002,193.580002,34014500,AAPL,2023-12-28
1,2023-12-27,192.490005,193.500000,191.089996,193.149994,193.149994,48087700,AAPL,2023-12-27
2,2023-12-26,193.610001,193.889999,192.830002,193.050003,193.050003,28919300,AAPL,2023-12-26
3,2023-12-22,195.179993,195.410004,192.970001,193.600006,193.600006,37122800,AAPL,2023-12-22
4,2023-12-21,196.100006,197.080002,193.500000,194.679993,194.679993,46482500,AAPL,2023-12-21
...,...,...,...,...,...,...,...,...,...
118319,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,TSLA,2010-07-06
118320,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,TSLA,2010-07-02
118321,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,TSLA,2010-07-01
118322,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,TSLA,2010-06-30
118323,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,TSLA,2010-06-29

In [60]:
filtered_prices_df["Date"].min()

Timestamp('2009-08-17 00:00:00')

In [62]:
filtered_prices_df.to_csv("Data/tech_prices.csv")